Merge pull request #1709 from swh/pm_partly_revert
Partly revert "Increase readability"

because of strange downstream issues
  orion/domains/localization/features/camera/camera_boundary_extractor.h:596:42: error: C-style casts are discouraged; use static_cast [google-readability-casting,-warnings-as-errors]
    596 |         typename CameraBoundaryExtractor<CameraSensor, Feature>::FeatureType feature;
        |                                          ^
        |                                          static_cast<>( )

GIT_ORIGIN_FUTURE_CPP_REV_ID: e10281cdf1d636e4298ac7e4f37e8727f7ba8ffe